# Generated by Django 4.2.4 on 2023-09-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_trainer_childrensection'),
    ]

    operations = [
        migrations.AddField(
            model_name='childrensection',
            name='record',
            field=models.BooleanField(default=False),
        ),
    ]
