# Generated by Django 4.2.4 on 2023-09-17 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_childrensection_rating_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilekid',
            name='id',
        ),
        migrations.AddField(
            model_name='profilekid',
            name='profile_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
