# Generated by Django 4.2.4 on 2023-09-17 06:13

from django.db import migrations, models
import django.db.models.deletion
import rest_framework.views


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_profilekid_id_profilekid_profile_ptr'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildrenSectionDetailAPIView',
            fields=[
                ('trainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.trainer')),
            ],
            bases=(rest_framework.views.APIView, 'core.trainer'),
        ),
    ]
