# Generated by Django 4.2.4 on 2023-09-17 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_childrensectiondetailapiview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childrensection',
            name='trainer',
        ),
        migrations.AddField(
            model_name='childrensection',
            name='trainer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='секции', to='core.trainer'),
            preserve_default=False,
        ),
    ]
