# Generated by Django 4.2.4 on 2023-09-17 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_childrensection_trainer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childrensection',
            name='trainer',
        ),
        migrations.AddField(
            model_name='childrensection',
            name='trainers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.trainer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='childrensection',
            name='club_kinds',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='ChildrenSectionDetailAPIView',
        ),
    ]
