# Generated by Django 4.2.4 on 2023-09-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_childrensection_trainer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='trainer_name',
            new_name='trainer',
        ),
    ]
