# Generated by Django 4.2.4 on 2023-09-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_trainer_name_trainer_trainer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childrensection',
            old_name='trainers',
            new_name='trainer',
        ),
    ]
