# Generated by Django 3.2.20 on 2023-09-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_trainer_trainer_trainer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childrensection',
            name='club_kinds',
            field=models.CharField(choices=[('1', 'спорт'), ('2', 'развитие'), ('3', 'искусство')], max_length=20),
        ),
    ]
